name: Push to GCP Artifact Registry

on:
    push:
        branches: ["gcp"]

permissions:
  id-token: write
  contents: read

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: 'actions/checkout@v4'

        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v2'
          with:
            workload_identity_provider: 'projects/1005967015769/locations/global/workloadIdentityPools/github-pool-test/providers/github-provider'
            service_account: 'ci-cd-sa@cultivated-era-468305-k7.iam.gserviceaccount.com'
        - id: 'deploy'
          uses: 'google-github-actions/deploy-cloudrun@v2'
          with:
            service: 'hello-cloud-run'
            image: 'gcr.io/cloudrun/hello'

        - name: 'Use output'
          run: 'curl "${{ steps.deploy.outputs.url }}"'
            